baseurl: "https://quantophile.github.io/mathsummaries/"
languageCode: "en-us"
title: "Math Summaries"
theme: "contrast-hugo"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
preserveTaxonomyNames: true
footnotereturnlinkcontents: "↩"
hasCJKLanguage: true
enableEmoji: true
paginate: 6

permalinks:
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: about/
      weight: 2
    - name: Categories
      url: categories/
      weight: 3
    - name: Tags
      url: tags/
      weight: 4
    - name: Subscribe
      url: index.xml

params:
  minimal: true
  excerpts : false
  description: I present here some quantitative finance projects that I have done or have been working on. Hope they can be of any help to you.""

  text:
    back: "&larr; Back to Home"
    edit: "Edit this page &rarr;"
    truncated: "&hellip;"

markup:
  highlight:
    codeFences: true
  goldmark:
    renderer:
      unsafe: true
